CREATE TABLE university_groups(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL
);

CREATE TABLE students(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    acceptance_date DATE NOT NULL,
    group_id BIGINT UNSIGNED,
    
    FOREIGN KEY (group_id) REFERENCES university_groups(id) 
    ON DELETE RESTRICT ON UPDATE RESTRICT
);